
  CREATE OR REPLACE EDITIONABLE VIEW dwh_dm."D_CERTIFICATE_VER" ("D_CERTIFICATE_VER_ID", "SUBFUND_KEY", "DM_SUBFUND_VER_ID", "EFFECTIVE_FROM", "EFFECTIVE_TO", "STATUS", "STATUS_VALUE", "STATUS_STEP", "STATUS_STEP_VALUE", "DWH_CREATED_DATE", "DWH_CREATED_BY", "DWH_CHANGED_DATE", "DWH_CHANGED_BY", "PARENT_KEY", "ACC_INVESTMENT_CURRENCY", "ACC_INVESTMENT_CURRENCY_VALUE", "BEN_OFFICIAL_NAME", "BEN_TYPE", "BEN_END_DATE", "BEN_PERF_EXPLORER", "BEN_PERF_EXPLORER_VALUE", "BEN_REBALANCING", "BEN_REBALANCING_VALUE", "BEN_START_DATE", "BEN_INITIAL_START_DATE", "CLO_ADVISOR_CLOSING_DATE", "CLO_ASSEMBLY_DATE", "CLO_BOARD_DECISION_DATE", "CLO_CLOSING_DESCRIPTION", "CLO_EXTRAORD_ASSEMBLE_DATE", "CLO_FSA_APPROVAL_DATE", "CLO_FSA_CLOSING_DATE", "CLO_FINAL_CLOSING_DATE", "CLO_LAST_ACCOUNT_YEAR_END", "CLO_LAST_ACCOUNT_YEAR_START", "CLO_LAST_OFF_NAV_DATE", "CLO_CREDITOR_NOTICE_START_DATE", "CLO_CREDITOR_NOTICE_END_DATE", "DIS_BLOOMBERG_ID", "DIS_DATA_TO_BLOOMBERG", "DIS_DATA_TO_MORNINGSTAR", "DIS_OFF_NAV_CUTOFF", "DIS_OFF_NAV_MORNING", "DIS_OFF_NAV_ONLINE", "DIS_ONLINE_NAV", "DIS_REUTERS_ID", "DIS_UNLISTED_NAV", "FEE_ACCT_YEAR_TER_APR", "FEE_ADMINISTRATION_FEE", "FEE_APR_EST", "FEE_AUDIT_FEE", "FEE_AUTHORITY_FEE", "FEE_CENTER_SHAREHOLDER_SERVICE", "FEE_CONVERSION_RATE", "FEE_DIMA_AIFM_FEE", "FEE_DISTRIBUTION_FEE", "FEE_DISTRIBUTION_FEE_GLOBAL", "FEE_DISTRIBUTION_FEE_INVESTOR", "FEE_DISTRIBUTION_FEE_SIN_INVES", "FEE_DOMICILE_FEE", "FEE_DOMICILE_FEE_INTERNAL", "FEE_ENTRY_CHARGE", "FEE_ENTRY_CHARGE_MAX", "FEE_EXIT_CHARGE", "FEE_EXIT_CHARGE_MAX", "FEE_MANAGEMENT_FEE", "FEE_MANAGEMENT_FEE_MAX", "FEE_MARKETING_FEE", "FEE_ONGOING_CHARGES_EST", "FEE_ONGOING_CHARGES_MAX", "FEE_OPERATING_ADMIN_EXPENSE", "FEE_OTHER_COSTS", "FEE_PARAGRAPH_51_AKTIEBOG", "FEE_PERFORMANCE_FEE", "FEE_PERFORMANCE_FEE_TEXT", "FEE_RED_BROKERAGE", "FEE_RED_FOREIGN_COST", "FEE_RED_MARKETING_FEE", "FEE_RED_ROUNDING_FACTOR", "FEE_RED_SPREAD_CURRENCY", "FEE_RED_SPREAD_RATE", "FEE_RED_TAXES", "FEE_RED_TRADE_COST", "FEE_RED_TRADE_COST_ROUNDED", "FEE_SALES_SUPPORT_FEE", "FEE_SUB_BROKERAGE", "FEE_SUB_FOREIGN_COST", "FEE_SUB_MARKETING_FEE", "FEE_SUB_SPREAD_CURRENCY", "FEE_SUB_SPREAD_RATE", "FEE_SUB_TAXES", "FEE_SUB_TRADE_COST", "FEE_SUB_TRADE_COST_ROUNDED", "FEE_TAX_DABONNEMENT", "FEE_TEGNINGSPROVISION", "FEE_TER_ACC", "FEE_TER_EST", "FEE_TER_MAX", "FEE_INDIRECT_TRADE_COST_EST", "FEE_ADMINISTRATION_FEE_MAX", "FEE_DIMC_CONTROL_FEE", "FEE_OPERATING_ADMIN_EXP_MAX", "FEE_RED_FEE_AGREED", "FEE_SUB_FEE_AGREED", "INV_CLASSIFICATION", "INV_COMPOSITE_DATE", "INV_COMPOSITE_NAME", "INV_COMPOSITE_SHORT_NAME", "INV_FX_HEDGE", "INV_FX_RESPONSIBLE", "INV_FX_SPOT", "INV_NEED_ORDER_APPROVAL", "INV_PCT_OF_TNA", "LEG_BOARD_DECISION_DATE", "LEG_CERTIFICATE_CURRENCY", "LEG_CERTIFICATE_CURRENCY_VALUE", "LEG_DISTRIBUTION_COUNTRY", "LEG_DISTRIBUTION_COUNTRY_VALUE", "LEG_EXCHANGE_START_DATE", "LEG_FORMATION_EXPENSE", "LEG_FSA_REGISTRATION_DATE", "LEG_FT_NO", "LEG_FULL_LEGAL_NAME", "LEG_GIIN", "LEG_INITIAL_PRICE", "LEG_ISIN", "LEG_LAUNCH_DATE", "LEG_LEI_CODE", "LEG_MARKETING_NAME", "LEG_MARKETING_NAME_WEB", "LEG_NAME", "LEG_NOMINAL_PER_CERTIFICATE", "LEG_OFFERING_END_DATE", "LEG_OFFERING_START_DATE", "LEG_ORG_NO", "LEG_PRICING_METHOD", "LEG_PRICING_METHOD_VALUE", "LEG_PSEUDO_SHORT_NAME", "LEG_REGISTER_IN_VP", "LEG_REPORTING_FT_NO", "LEG_SECURITY_ID", "LEG_SUBFUND_LEGAL_STATUS", "LEG_SUBFUND_LEGAL_STATUS_VALUE", "LEG_SUBFUND_LEGAL_TYPE", "LEG_SUBFUND_LEGAL_TYPE_VALUE", "LEG_TYPE_OF_CLASS", "LEG_TYPE_OF_CLASS_VALUE", "LEG_VALOREN", "LEG_WKN", "MER_ASSEMBLY_DATE", "MER_BOARD_DECISION_DATE", "MER_CONTINUED", "MER_CONTINUED_VALUE", "MER_DESCRIPTION", "MER_DISCONTINUED", "MER_DISCONTINUED_VALUE", "MER_EXCHANGE_RATIO", "MER_EXTRAORD_ASSEMBLY_DATE", "MER_FSA_APPROVAL_DATE", "MER_LAST_ACCOUNT_YEAR_END", "MER_LAST_ACCOUNT_YEAR_START", "MER_LAST_OFF_NAV_DATE", "MER_LAST_OFF_TRADE_DATE", "MER_NAV_ON_CONTINUED", "MER_NAV_ON_DISCONTINUED", "MER_PERFORM_VP_DATE", "MER_PROCESS_DESCRIPTION_DATE", "MER_TAX_FREE", "MER_TAX_IMPLEMENT_DATE", "MER_SECURITY_ID_CONTINUED", "MER_SECURITY_ID_DISCONTINUED", "STR_CLOSE_OPEN_ENDED", "STR_CLOSE_OPEN_ENDED_VALUE", "STR_FUND_KEY", "STR_INCOME_DISTRIBUTION", "STR_INCOME_DISTRIBUTION_VALUE", "STR_INVISION_CODE", "STR_MIN_INI_INV_AMT", "STR_MIN_INI_INV_UNIT", "STR_MODEL_PORTFOLIO", "STR_SHORT_NAME", "STR_SUBFUND_STRUCTURE", "STR_SUBFUND_STRUCTURE_VALUE", "STR_SUBFUND_STRUCTURE_TYPE", "STR_SUBFUND_STRUCTURE_TYPE_VAL", "STR_DM_SUBFUND_TYPE_ID", "STR_INTERIM_INCOME_DIST", "STR_SUBFUND_STATUS_DORMANT", "STR_DORMANT_START_DATE", "STR_DORMANT_END_DATE", "STR_ACTIVE_INACTIVE", "TAX_SOCIAL_HOUSING", "TAX_SHARE_PRICE_19MAY1993", "TAX_EU_SAVINGS_DIRECTIVE", "TAX_FINI_NUMBER", "TAX_FUND_AND_SCHOLARSHIP", "TAX_PRIVATE_FREE_SAVING", "TAX_FREE_SAVING", "TAX_MUNICIPALITY", "TAX_SHARE_PRICE_19MAY1993_COR", "TAX_ONLY_FLEX_FREE", "TAX_NTN_NUMBER", "TAX_PENSION_SAVING", "TAX_REG_AUSTRAIN_TAX", "TAX_REG_GERMAN_TAX", "TAX_COMPANIES", "TAX_COMPANY_TAXATION", "TRA_AGREED_DEADLINE", "TRA_CALC_DAY", "TRA_CONTRACT", "TRA_CUT_OFF", "TRA_CUT_OFF_VALUE", "TRA_MARKET_MAKER_DC_INCL_FLEX", "TRA_DS_AC_NO", "TRA_MARKET_MAKER_DANSKE", "TRA_DECIMAL_PLACES_NAV", "TRA_DECIMAL_ROUNDING", "TRA_LISTED", "TRA_MIN_INV_AMT", "TRA_MIN_INV_UNIT", "TRA_MULTIFUNDS", "TRA_NAV_FREQ", "TRA_OMX_ID", "TRA_PTG", "TRA_SARA_CODE", "TRA_SETTL_TERMS_SUB", "TRA_SETTL_TERMS_UND", "TRA_SUB_EX_COUPON_CORR_FACTOR", "TRA_SUB_INACTIVE", "TRA_VALUATION_POINT", "TRA_SETTL_TERMS_RED", "TRA_INCLUDE_IN_PRIS", "SUB_SUBFUND_TYPE", "SUB_SUBFUND_TYPE_CODE", "SUB_ENTITY_LEVEL", "SUB_STATUS", "VER", "RANK_NEWEST_VERSION", "INV_FX_SPOT_VIA_CLS", "INV_FX_FWD_VIA_CLS", "LEG_RESERVED_PM_AGREEMENTS", "LEG_NOTICE_PERIOD", "LEG_LOCK_UP_PERIOD", "LEG_SPECIAL_TREATMENT", "LEG_INVESTOR_GRP1", "LEG_INVESTOR_GRP1_PCT", "LEG_INVESTOR_GRP2", "LEG_INVESTOR_GRP2_PCT", "LEG_INVESTOR_GRP3", "LEG_INVESTOR_GRP3_PCT", "LEG_INVESTOR_GRP4", "LEG_INVESTOR_GRP4_PCT", "LEG_INVESTOR_GRP5", "LEG_INVESTOR_GRP5_PCT", "STR_MOTIVE_CLASS", "STR_OPEN_ACCESS", "STR_ADVISORY_SERVICES_INCL", "DRAFT_CHANGED_DATE", "MER_TECHNICAL_MERGER", "LEG_FULL_LEGAL_NAME_NORM", "LEG_MARKETING_NAME_NORM", "LEG_NAME_NORM", "LEG_MARKETING_NAME_WEB_NORM") AS SELECT "D_CERTIFICATE_VER_ID",
       "SUBFUND_KEY",
       "DM_SUBFUND_VER_ID",
       "EFFECTIVE_FROM",
       "EFFECTIVE_TO",
       "STATUS",
       "STATUS_VALUE",
       "STATUS_STEP",
       "STATUS_STEP_VALUE",
       "DWH_CREATED_DATE",
       "DWH_CREATED_BY",
       "DWH_CHANGED_DATE",
       "DWH_CHANGED_BY",
       "PARENT_KEY",
       "ACC_INVESTMENT_CURRENCY",
       "ACC_INVESTMENT_CURRENCY_VALUE",
       "BEN_OFFICIAL_NAME",
       "BEN_TYPE",
       "BEN_END_DATE",
       "BEN_PERF_EXPLORER",
       "BEN_PERF_EXPLORER_VALUE",
       "BEN_REBALANCING",
       "BEN_REBALANCING_VALUE",
       "BEN_START_DATE",
       "BEN_INITIAL_START_DATE",
       "CLO_ADVISOR_CLOSING_DATE",
       "CLO_ASSEMBLY_DATE",
       "CLO_BOARD_DECISION_DATE",
       "CLO_CLOSING_DESCRIPTION",
       "CLO_EXTRAORD_ASSEMBLE_DATE",
       "CLO_FSA_APPROVAL_DATE",
       "CLO_FSA_CLOSING_DATE",
       "CLO_FINAL_CLOSING_DATE",
       "CLO_LAST_ACCOUNT_YEAR_END",
       "CLO_LAST_ACCOUNT_YEAR_START",
       "CLO_LAST_OFF_NAV_DATE",
       "CLO_CREDITOR_NOTICE_START_DATE",
       "CLO_CREDITOR_NOTICE_END_DATE",
       "DIS_BLOOMBERG_ID",
       "DIS_DATA_TO_BLOOMBERG",
       "DIS_DATA_TO_MORNINGSTAR",
       "DIS_OFF_NAV_CUTOFF",
       "DIS_OFF_NAV_MORNING",
       "DIS_OFF_NAV_ONLINE",
       "DIS_ONLINE_NAV",
       "DIS_REUTERS_ID",
       "DIS_UNLISTED_NAV",
       "FEE_ACCT_YEAR_TER_APR",
       "FEE_ADMINISTRATION_FEE",
       --       "FEE_APR_ACC",
       "FEE_APR_EST",
       "FEE_AUDIT_FEE",
       "FEE_AUTHORITY_FEE",
       "FEE_CENTER_SHAREHOLDER_SERVICE",
       "FEE_CONVERSION_RATE",
       "FEE_DIMA_AIFM_FEE",
       "FEE_DISTRIBUTION_FEE",
       "FEE_DISTRIBUTION_FEE_GLOBAL",
       "FEE_DISTRIBUTION_FEE_INVESTOR",
       "FEE_DISTRIBUTION_FEE_SIN_INVES",
       "FEE_DOMICILE_FEE",
       "FEE_DOMICILE_FEE_INTERNAL",
       "FEE_ENTRY_CHARGE",
       "FEE_ENTRY_CHARGE_MAX",
       "FEE_EXIT_CHARGE",
       "FEE_EXIT_CHARGE_MAX",
       "FEE_MANAGEMENT_FEE",
       "FEE_MANAGEMENT_FEE_MAX",
       "FEE_MARKETING_FEE",
       --       "FEE_ONGOING_CHARGES_ACC",
       "FEE_ONGOING_CHARGES_EST",
       "FEE_ONGOING_CHARGES_MAX",
       "FEE_OPERATING_ADMIN_EXPENSE",
       "FEE_OTHER_COSTS",
       "FEE_PARAGRAPH_51_AKTIEBOG",
       "FEE_PERFORMANCE_FEE",
       "FEE_PERFORMANCE_FEE_TEXT",
       "FEE_RED_BROKERAGE",
       "FEE_RED_FOREIGN_COST",
       "FEE_RED_MARKETING_FEE",
       "FEE_RED_ROUNDING_FACTOR",
       "FEE_RED_SPREAD_CURRENCY",
       "FEE_RED_SPREAD_RATE",
       "FEE_RED_TAXES",
       "FEE_RED_TRADE_COST",
       "FEE_RED_TRADE_COST_ROUNDED",
       "FEE_SALES_SUPPORT_FEE",
       "FEE_SUB_BROKERAGE",
       "FEE_SUB_FOREIGN_COST",
       "FEE_SUB_MARKETING_FEE",
       "FEE_SUB_SPREAD_CURRENCY",
       "FEE_SUB_SPREAD_RATE",
       "FEE_SUB_TAXES",
       "FEE_SUB_TRADE_COST",
       "FEE_SUB_TRADE_COST_ROUNDED",
       "FEE_TAX_DABONNEMENT",
       "FEE_TEGNINGSPROVISION",
       "FEE_TER_ACC",
       "FEE_TER_EST",
       "FEE_TER_MAX",
       "FEE_INDIRECT_TRADE_COST_EST",
       --       "FEE_INDIRECT_TRADE_COST_ACC",
 "FEE_ADMINISTRATION_FEE_MAX",
 "FEE_DIMC_CONTROL_FEE",
 "FEE_OPERATING_ADMIN_EXP_MAX",
 "FEE_RED_FEE_AGREED",
 "FEE_SUB_FEE_AGREED",
       "INV_CLASSIFICATION",
       "INV_COMPOSITE_DATE",
       "INV_COMPOSITE_NAME",
       "INV_COMPOSITE_SHORT_NAME",
       "INV_FX_HEDGE",
       "INV_FX_RESPONSIBLE",
       "INV_FX_SPOT",
       "INV_NEED_ORDER_APPROVAL",
       "INV_PCT_OF_TNA",
       "LEG_BOARD_DECISION_DATE",
       "LEG_CERTIFICATE_CURRENCY",
       "LEG_CERTIFICATE_CURRENCY_VALUE",
       "LEG_DISTRIBUTION_COUNTRY",
       "LEG_DISTRIBUTION_COUNTRY_VALUE",
       "LEG_EXCHANGE_START_DATE",
       "LEG_FORMATION_EXPENSE",
       "LEG_FSA_REGISTRATION_DATE",
       "LEG_FT_NO",
       "LEG_FULL_LEGAL_NAME",
       "LEG_GIIN",
       "LEG_INITIAL_PRICE",
       "LEG_ISIN",
       "LEG_LAUNCH_DATE",
       "LEG_LEI_CODE",
       "LEG_MARKETING_NAME",
       "LEG_MARKETING_NAME_WEB",
       "LEG_NAME",
       "LEG_NOMINAL_PER_CERTIFICATE",
       "LEG_OFFERING_END_DATE",
       "LEG_OFFERING_START_DATE",
       "LEG_ORG_NO",
       "LEG_PRICING_METHOD",
       "LEG_PRICING_METHOD_VALUE",
       "LEG_PSEUDO_SHORT_NAME",
       "LEG_REGISTER_IN_VP",
       "LEG_REPORTING_FT_NO",
       "LEG_SECURITY_ID",
       "LEG_SUBFUND_LEGAL_STATUS",
       "LEG_SUBFUND_LEGAL_STATUS_VALUE",
       "LEG_SUBFUND_LEGAL_TYPE",
       "LEG_SUBFUND_LEGAL_TYPE_VALUE",
       "LEG_TYPE_OF_CLASS",
       "LEG_TYPE_OF_CLASS_VALUE",
       "LEG_VALOREN",
       "LEG_WKN",
       "MER_ASSEMBLY_DATE",
       "MER_BOARD_DECISION_DATE",
       "MER_CONTINUED",
       "MER_CONTINUED_VALUE",
       "MER_DESCRIPTION",
       "MER_DISCONTINUED",
       "MER_DISCONTINUED_VALUE",
       "MER_EXCHANGE_RATIO",
       "MER_EXTRAORD_ASSEMBLY_DATE",
       "MER_FSA_APPROVAL_DATE",
       "MER_LAST_ACCOUNT_YEAR_END",
       "MER_LAST_ACCOUNT_YEAR_START",
       "MER_LAST_OFF_NAV_DATE",
       "MER_LAST_OFF_TRADE_DATE",
       "MER_NAV_ON_CONTINUED",
       "MER_NAV_ON_DISCONTINUED",
       "MER_PERFORM_VP_DATE",
       "MER_PROCESS_DESCRIPTION_DATE",
       "MER_TAX_FREE",
       "MER_TAX_IMPLEMENT_DATE",
       "MER_SECURITY_ID_CONTINUED",
       "MER_SECURITY_ID_DISCONTINUED",
       "STR_CLOSE_OPEN_ENDED",
       "STR_CLOSE_OPEN_ENDED_VALUE",
       "STR_FUND_KEY",
       "STR_INCOME_DISTRIBUTION",
       "STR_INCOME_DISTRIBUTION_VALUE",
       "STR_INVISION_CODE",
       "STR_MIN_INI_INV_AMT",
       "STR_MIN_INI_INV_UNIT",
       "STR_MODEL_PORTFOLIO",
       "STR_SHORT_NAME",
       "STR_SUBFUND_STRUCTURE",
       "STR_SUBFUND_STRUCTURE_VALUE",
       "STR_SUBFUND_STRUCTURE_TYPE",
       "STR_SUBFUND_STRUCTURE_TYPE_VAL",
       "STR_DM_SUBFUND_TYPE_ID",
       "STR_INTERIM_INCOME_DIST",
       "STR_SUBFUND_STATUS_DORMANT",
       "STR_DORMANT_START_DATE",
       "STR_DORMANT_END_DATE",
       "STR_ACTIVE_INACTIVE",
       "TAX_SOCIAL_HOUSING",
       "TAX_SHARE_PRICE_19MAY1993",
       "TAX_EU_SAVINGS_DIRECTIVE",
       "TAX_FINI_NUMBER",
       "TAX_FUND_AND_SCHOLARSHIP",
       "TAX_PRIVATE_FREE_SAVING",
       "TAX_FREE_SAVING",
       "TAX_MUNICIPALITY",
       "TAX_SHARE_PRICE_19MAY1993_COR",
       "TAX_ONLY_FLEX_FREE",
       "TAX_NTN_NUMBER",
       "TAX_PENSION_SAVING",
       "TAX_REG_AUSTRAIN_TAX",
       "TAX_REG_GERMAN_TAX",
       "TAX_COMPANIES",
       "TAX_COMPANY_TAXATION",
       "TRA_AGREED_DEADLINE",
       "TRA_CALC_DAY",
       "TRA_CONTRACT",
       "TRA_CUT_OFF",
       "TRA_CUT_OFF_VALUE",
       "TRA_MARKET_MAKER_DC_INCL_FLEX",
       "TRA_DS_AC_NO",
       "TRA_MARKET_MAKER_DANSKE",
       "TRA_DECIMAL_PLACES_NAV",
       "TRA_DECIMAL_ROUNDING",
       "TRA_LISTED",
       "TRA_MIN_INV_AMT",
       "TRA_MIN_INV_UNIT",
       "TRA_MULTIFUNDS",
       "TRA_NAV_FREQ",
       "TRA_OMX_ID",
       "TRA_PTG",
       "TRA_SARA_CODE",
       "TRA_SETTL_TERMS_SUB",
       "TRA_SETTL_TERMS_UND",
       "TRA_SUB_EX_COUPON_CORR_FACTOR",
       "TRA_SUB_INACTIVE",
       "TRA_VALUATION_POINT",
       "TRA_SETTL_TERMS_RED",
       "TRA_INCLUDE_IN_PRIS",
       "SUB_SUBFUND_TYPE",
       "SUB_SUBFUND_TYPE_CODE",
       "SUB_ENTITY_LEVEL",
       "SUB_STATUS",
       1 "VER",
       "RANK_NEWEST_VERSION",
       "INV_FX_SPOT_VIA_CLS",
       "INV_FX_FWD_VIA_CLS",
       "LEG_RESERVED_PM_AGREEMENTS",
       "LEG_NOTICE_PERIOD",
       "LEG_LOCK_UP_PERIOD",
       "LEG_SPECIAL_TREATMENT",
       "LEG_INVESTOR_GRP1",
       "LEG_INVESTOR_GRP1_PCT",
       "LEG_INVESTOR_GRP2",
       "LEG_INVESTOR_GRP2_PCT",
       "LEG_INVESTOR_GRP3",
       "LEG_INVESTOR_GRP3_PCT",
       "LEG_INVESTOR_GRP4",
       "LEG_INVESTOR_GRP4_PCT",
       "LEG_INVESTOR_GRP5",
       "LEG_INVESTOR_GRP5_PCT",
       "STR_MOTIVE_CLASS",
       "STR_OPEN_ACCESS",
       "STR_ADVISORY_SERVICES_INCL",
       DRAFT_CHANGED_DATE,
       "MER_TECHNICAL_MERGER"
,leg_full_legal_name_norm
,leg_marketing_name_norm
,leg_name_norm
,leg_marketing_name_web_norm
  FROM D_CERTIFICATE_VER_1
 WHERE ( SELECT ver
           FROM flm_load_control_ver ) = 1
UNION ALL
SELECT "D_CERTIFICATE_VER_ID",
       "SUBFUND_KEY",
       "DM_SUBFUND_VER_ID",
       "EFFECTIVE_FROM",
       "EFFECTIVE_TO",
       "STATUS",
       "STATUS_VALUE",
       "STATUS_STEP",
       "STATUS_STEP_VALUE",
       "DWH_CREATED_DATE",
       "DWH_CREATED_BY",
       "DWH_CHANGED_DATE",
       "DWH_CHANGED_BY",
       "PARENT_KEY",
       "ACC_INVESTMENT_CURRENCY",
       "ACC_INVESTMENT_CURRENCY_VALUE",
       "BEN_OFFICIAL_NAME",
       "BEN_TYPE",
       "BEN_END_DATE",
       "BEN_PERF_EXPLORER",
       "BEN_PERF_EXPLORER_VALUE",
       "BEN_REBALANCING",
       "BEN_REBALANCING_VALUE",
       "BEN_START_DATE",
       "BEN_INITIAL_START_DATE",
       "CLO_ADVISOR_CLOSING_DATE",
       "CLO_ASSEMBLY_DATE",
       "CLO_BOARD_DECISION_DATE",
       "CLO_CLOSING_DESCRIPTION",
       "CLO_EXTRAORD_ASSEMBLE_DATE",
       "CLO_FSA_APPROVAL_DATE",
       "CLO_FSA_CLOSING_DATE",
       "CLO_FINAL_CLOSING_DATE",
       "CLO_LAST_ACCOUNT_YEAR_END",
       "CLO_LAST_ACCOUNT_YEAR_START",
       "CLO_LAST_OFF_NAV_DATE",
       "CLO_CREDITOR_NOTICE_START_DATE",
       "CLO_CREDITOR_NOTICE_END_DATE",
       "DIS_BLOOMBERG_ID",
       "DIS_DATA_TO_BLOOMBERG",
       "DIS_DATA_TO_MORNINGSTAR",
       "DIS_OFF_NAV_CUTOFF",
       "DIS_OFF_NAV_MORNING",
       "DIS_OFF_NAV_ONLINE",
       "DIS_ONLINE_NAV",
       "DIS_REUTERS_ID",
       "DIS_UNLISTED_NAV",
       "FEE_ACCT_YEAR_TER_APR",
       "FEE_ADMINISTRATION_FEE",
       --       "FEE_APR_ACC",
       "FEE_APR_EST",
       "FEE_AUDIT_FEE",
       "FEE_AUTHORITY_FEE",
       "FEE_CENTER_SHAREHOLDER_SERVICE",
       "FEE_CONVERSION_RATE",
       "FEE_DIMA_AIFM_FEE",
       "FEE_DISTRIBUTION_FEE",
       "FEE_DISTRIBUTION_FEE_GLOBAL",
       "FEE_DISTRIBUTION_FEE_INVESTOR",
       "FEE_DISTRIBUTION_FEE_SIN_INVES",
       "FEE_DOMICILE_FEE",
       "FEE_DOMICILE_FEE_INTERNAL",
       "FEE_ENTRY_CHARGE",
       "FEE_ENTRY_CHARGE_MAX",
       "FEE_EXIT_CHARGE",
       "FEE_EXIT_CHARGE_MAX",
       "FEE_MANAGEMENT_FEE",
       "FEE_MANAGEMENT_FEE_MAX",
       "FEE_MARKETING_FEE",
       --       "FEE_ONGOING_CHARGES_ACC",
       "FEE_ONGOING_CHARGES_EST",
       "FEE_ONGOING_CHARGES_MAX",
       "FEE_OPERATING_ADMIN_EXPENSE",
       "FEE_OTHER_COSTS",
       "FEE_PARAGRAPH_51_AKTIEBOG",
       "FEE_PERFORMANCE_FEE",
       "FEE_PERFORMANCE_FEE_TEXT",
       "FEE_RED_BROKERAGE",
       "FEE_RED_FOREIGN_COST",
       "FEE_RED_MARKETING_FEE",
       "FEE_RED_ROUNDING_FACTOR",
       "FEE_RED_SPREAD_CURRENCY",
       "FEE_RED_SPREAD_RATE",
       "FEE_RED_TAXES",
       "FEE_RED_TRADE_COST",
       "FEE_RED_TRADE_COST_ROUNDED",
       "FEE_SALES_SUPPORT_FEE",
       "FEE_SUB_BROKERAGE",
       "FEE_SUB_FOREIGN_COST",
       "FEE_SUB_MARKETING_FEE",
       "FEE_SUB_SPREAD_CURRENCY",
       "FEE_SUB_SPREAD_RATE",
       "FEE_SUB_TAXES",
       "FEE_SUB_TRADE_COST",
       "FEE_SUB_TRADE_COST_ROUNDED",
       "FEE_TAX_DABONNEMENT",
       "FEE_TEGNINGSPROVISION",
       "FEE_TER_ACC",
       "FEE_TER_EST",
       "FEE_TER_MAX",
       "FEE_INDIRECT_TRADE_COST_EST",
       --      "FEE_INDIRECT_TRADE_COST_ACC",
 "FEE_ADMINISTRATION_FEE_MAX",
 "FEE_DIMC_CONTROL_FEE",
 "FEE_OPERATING_ADMIN_EXP_MAX",
 "FEE_RED_FEE_AGREED",
 "FEE_SUB_FEE_AGREED",
       "INV_CLASSIFICATION",
       "INV_COMPOSITE_DATE",
       "INV_COMPOSITE_NAME",
       "INV_COMPOSITE_SHORT_NAME",
       "INV_FX_HEDGE",
       "INV_FX_RESPONSIBLE",
       "INV_FX_SPOT",
       "INV_NEED_ORDER_APPROVAL",
       "INV_PCT_OF_TNA",
       "LEG_BOARD_DECISION_DATE",
       "LEG_CERTIFICATE_CURRENCY",
       "LEG_CERTIFICATE_CURRENCY_VALUE",
       "LEG_DISTRIBUTION_COUNTRY",
       "LEG_DISTRIBUTION_COUNTRY_VALUE",
       "LEG_EXCHANGE_START_DATE",
       "LEG_FORMATION_EXPENSE",
       "LEG_FSA_REGISTRATION_DATE",
       "LEG_FT_NO",
       "LEG_FULL_LEGAL_NAME",
       "LEG_GIIN",
       "LEG_INITIAL_PRICE",
       "LEG_ISIN",
       "LEG_LAUNCH_DATE",
       "LEG_LEI_CODE",
       "LEG_MARKETING_NAME",
       "LEG_MARKETING_NAME_WEB",
       "LEG_NAME",
       "LEG_NOMINAL_PER_CERTIFICATE",
       "LEG_OFFERING_END_DATE",
       "LEG_OFFERING_START_DATE",
       "LEG_ORG_NO",
       "LEG_PRICING_METHOD",
       "LEG_PRICING_METHOD_VALUE",
       "LEG_PSEUDO_SHORT_NAME",
       "LEG_REGISTER_IN_VP",
       "LEG_REPORTING_FT_NO",
       "LEG_SECURITY_ID",
       "LEG_SUBFUND_LEGAL_STATUS",
       "LEG_SUBFUND_LEGAL_STATUS_VALUE",
       "LEG_SUBFUND_LEGAL_TYPE",
       "LEG_SUBFUND_LEGAL_TYPE_VALUE",
       "LEG_TYPE_OF_CLASS",
       "LEG_TYPE_OF_CLASS_VALUE",
       "LEG_VALOREN",
       "LEG_WKN",
       "MER_ASSEMBLY_DATE",
       "MER_BOARD_DECISION_DATE",
       "MER_CONTINUED",
       "MER_CONTINUED_VALUE",
       "MER_DESCRIPTION",
       "MER_DISCONTINUED",
       "MER_DISCONTINUED_VALUE",
       "MER_EXCHANGE_RATIO",
       "MER_EXTRAORD_ASSEMBLY_DATE",
       "MER_FSA_APPROVAL_DATE",
       "MER_LAST_ACCOUNT_YEAR_END",
       "MER_LAST_ACCOUNT_YEAR_START",
       "MER_LAST_OFF_NAV_DATE",
       "MER_LAST_OFF_TRADE_DATE",
       "MER_NAV_ON_CONTINUED",
       "MER_NAV_ON_DISCONTINUED",
       "MER_PERFORM_VP_DATE",
       "MER_PROCESS_DESCRIPTION_DATE",
       "MER_TAX_FREE",
       "MER_TAX_IMPLEMENT_DATE",
       "MER_SECURITY_ID_CONTINUED",
       "MER_SECURITY_ID_DISCONTINUED",
       "STR_CLOSE_OPEN_ENDED",
       "STR_CLOSE_OPEN_ENDED_VALUE",
       "STR_FUND_KEY",
       "STR_INCOME_DISTRIBUTION",
       "STR_INCOME_DISTRIBUTION_VALUE",
       "STR_INVISION_CODE",
       "STR_MIN_INI_INV_AMT",
       "STR_MIN_INI_INV_UNIT",
       "STR_MODEL_PORTFOLIO",
       "STR_SHORT_NAME",
       "STR_SUBFUND_STRUCTURE",
       "STR_SUBFUND_STRUCTURE_VALUE",
       "STR_SUBFUND_STRUCTURE_TYPE",
       "STR_SUBFUND_STRUCTURE_TYPE_VAL",
       "STR_DM_SUBFUND_TYPE_ID",
       "STR_INTERIM_INCOME_DIST",
       "STR_SUBFUND_STATUS_DORMANT",
       "STR_DORMANT_START_DATE",
       "STR_DORMANT_END_DATE",
       "STR_ACTIVE_INACTIVE",
       "TAX_SOCIAL_HOUSING",
       "TAX_SHARE_PRICE_19MAY1993",
       "TAX_EU_SAVINGS_DIRECTIVE",
       "TAX_FINI_NUMBER",
       "TAX_FUND_AND_SCHOLARSHIP",
       "TAX_PRIVATE_FREE_SAVING",
       "TAX_FREE_SAVING",
       "TAX_MUNICIPALITY",
       "TAX_SHARE_PRICE_19MAY1993_COR",
       "TAX_ONLY_FLEX_FREE",
       "TAX_NTN_NUMBER",
       "TAX_PENSION_SAVING",
       "TAX_REG_AUSTRAIN_TAX",
       "TAX_REG_GERMAN_TAX",
       "TAX_COMPANIES",
       "TAX_COMPANY_TAXATION",
       "TRA_AGREED_DEADLINE",
       "TRA_CALC_DAY",
       "TRA_CONTRACT",
       "TRA_CUT_OFF",
       "TRA_CUT_OFF_VALUE",
       "TRA_MARKET_MAKER_DC_INCL_FLEX",
       "TRA_DS_AC_NO",
       "TRA_MARKET_MAKER_DANSKE",
       "TRA_DECIMAL_PLACES_NAV",
       "TRA_DECIMAL_ROUNDING",
       "TRA_LISTED",
       "TRA_MIN_INV_AMT",
       "TRA_MIN_INV_UNIT",
       "TRA_MULTIFUNDS",
       "TRA_NAV_FREQ",
       "TRA_OMX_ID",
       "TRA_PTG",
       "TRA_SARA_CODE",
       "TRA_SETTL_TERMS_SUB",
       "TRA_SETTL_TERMS_UND",
       "TRA_SUB_EX_COUPON_CORR_FACTOR",
       "TRA_SUB_INACTIVE",
       "TRA_VALUATION_POINT",
       "TRA_SETTL_TERMS_RED",
       "TRA_INCLUDE_IN_PRIS",
       "SUB_SUBFUND_TYPE",
       "SUB_SUBFUND_TYPE_CODE",
       "SUB_ENTITY_LEVEL",
       "SUB_STATUS",
       2 "VER",
       "RANK_NEWEST_VERSION",
       "INV_FX_SPOT_VIA_CLS",
       "INV_FX_FWD_VIA_CLS",
       "LEG_RESERVED_PM_AGREEMENTS",
       "LEG_NOTICE_PERIOD",
       "LEG_LOCK_UP_PERIOD",
       "LEG_SPECIAL_TREATMENT",
       "LEG_INVESTOR_GRP1",
       "LEG_INVESTOR_GRP1_PCT",
       "LEG_INVESTOR_GRP2",
       "LEG_INVESTOR_GRP2_PCT",
       "LEG_INVESTOR_GRP3",
       "LEG_INVESTOR_GRP3_PCT",
       "LEG_INVESTOR_GRP4",
       "LEG_INVESTOR_GRP4_PCT",
       "LEG_INVESTOR_GRP5",
       "LEG_INVESTOR_GRP5_PCT",
       "STR_MOTIVE_CLASS",
       "STR_OPEN_ACCESS",
       "STR_ADVISORY_SERVICES_INCL",
       DRAFT_CHANGED_DATE,
       "MER_TECHNICAL_MERGER"
,leg_full_legal_name_norm
,leg_marketing_name_norm
,leg_name_norm
,leg_marketing_name_web_norm
  FROM D_CERTIFICATE_VER_2
 WHERE ( SELECT ver
           FROM flm_load_control_ver ) = 2

;

   COMMENT ON COLUMN "D_CERTIFICATE_VER"."ACC_INVESTMENT_CURRENCY" IS 'Investment Currency #FLM: dm_accounting.investment_currency';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."BEN_OFFICIAL_NAME" IS 'Official Name #FLM: dm_benchmark.official_name';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."BEN_TYPE" IS 'Benchmark #FLM: dm_benchmark.type';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."BEN_END_DATE" IS 'Benchmark End Date #FLM: dm_benchmark.end_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."BEN_PERF_EXPLORER" IS 'Performance Explorer #FLM: dm_benchmark.perf_explorer';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."BEN_REBALANCING" IS 'Rebalancing #FLM: dm_benchmark.rebalancing';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."BEN_START_DATE" IS 'Benchmark Start Date #FLM: dm_benchmark.start_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."BEN_INITIAL_START_DATE" IS 'Initial Benchmark Start Date #FLM: dm_benchmark.initial_start_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."CLO_ADVISOR_CLOSING_DATE" IS 'Advisor Closing Date #FLM: dm_closing.advisor_closing_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."CLO_ASSEMBLY_DATE" IS 'Assembly Date #FLM: dm_closing.assembly_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."CLO_BOARD_DECISION_DATE" IS 'Board Decision Date #FLM: dm_closing.board_decision_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."CLO_CLOSING_DESCRIPTION" IS 'Closing Description #FLM: dm_closing.closing_description';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."CLO_EXTRAORD_ASSEMBLE_DATE" IS 'Extraord. Assembly Date #FLM: dm_closing.extraord_assemble_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."CLO_FSA_APPROVAL_DATE" IS 'FSA Approval Date #FLM: dm_closing.fsa_approval_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."CLO_FSA_CLOSING_DATE" IS 'FSA Closing Date #FLM: dm_closing.fsa_closing_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."CLO_FINAL_CLOSING_DATE" IS 'Final Closing Date #FLM: dm_closing.final_closing_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."CLO_LAST_ACCOUNT_YEAR_END" IS 'Last Accounting Year End #FLM: dm_closing.last_account_year_end';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."CLO_LAST_ACCOUNT_YEAR_START" IS 'Last Accounting Year Start #FLM: dm_closing.last_account_year_start';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."CLO_LAST_OFF_NAV_DATE" IS 'Last Official NAV Date #FLM: dm_closing.last_off_nav_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."CLO_CREDITOR_NOTICE_START_DATE" IS 'Notice to Creditors Start Date #FLM: dm_closing.creditor_notice_start_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."CLO_CREDITOR_NOTICE_END_DATE" IS 'Notice to Creditors End Date #FLM: dm_closing.creditor_notice_end_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_ACCT_YEAR_TER_APR" IS 'Accounting Year for TER and APR #FLM: dm_fee.acct_year_ter_apr';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_ADMINISTRATION_FEE" IS 'Administration Fee #FLM: dm_fee.administration_fee';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_APR_EST" IS 'Annual Percentage Rate - APR (Estimates) #FLM: dm_fee.apr_est';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_AUDIT_FEE" IS 'Audit Fee #FLM: dm_fee.audit_fee';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_AUTHORITY_FEE" IS 'Authority Fee #FLM: dm_fee.authority_fee';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_CENTER_SHAREHOLDER_SERVICE" IS 'Centralized Shareholder Service #FLM: dm_fee.center_shareholder_service';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_CONVERSION_RATE" IS 'Conversion Rate #FLM: dm_fee.conversion_rate';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_DIMA_AIFM_FEE" IS 'DIMA AIFM Fee #FLM: dm_fee.dima_aifm_fee';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_DISTRIBUTION_FEE" IS 'Distribution Fee #FLM: dm_fee.distribution_fee';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_DISTRIBUTION_FEE_GLOBAL" IS 'Distribution Fee (Global) #FLM: dm_fee.distribution_fee_global';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_DISTRIBUTION_FEE_INVESTOR" IS 'Distribution Fee (Investor) #FLM: dm_fee.distribution_fee_investor';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_DOMICILE_FEE" IS 'Domicile Fee #FLM: dm_fee.domicile_fee';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_DOMICILE_FEE_INTERNAL" IS 'Domicile Fee (Internal) #FLM: dm_fee.domicile_fee_internal';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_ENTRY_CHARGE" IS 'Subscription Entry Charge #FLM: dm_fee.entry_charge';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_ENTRY_CHARGE_MAX" IS 'Subscription Entry Charge (Maximum) #FLM: dm_fee.entry_charge_max';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_EXIT_CHARGE" IS 'Redemption Exit Charge #FLM: dm_fee.exit_charge';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_EXIT_CHARGE_MAX" IS 'Redemption Exit Charge (Maximum) #FLM: dm_fee.exit_charge_max';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_MANAGEMENT_FEE" IS 'Management Fee #FLM: dm_fee.management_fee';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_MANAGEMENT_FEE_MAX" IS 'Management Fee (Maximum) #FLM: dm_fee.management_fee_max';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_MARKETING_FEE" IS 'Marketing Fee #FLM: dm_fee.marketing_fee';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_ONGOING_CHARGES_EST" IS 'Ongoing Charges (Estimates) #FLM: dm_fee.ongoing_charges_est';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_ONGOING_CHARGES_MAX" IS 'Ongoing Charges (Maximum) #FLM: dm_fee.ongoing_charges_max';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_OPERATING_ADMIN_EXPENSE" IS 'Operating & Admin. Expense #FLM: dm_fee.operating_admin_expense';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_OTHER_COSTS" IS 'Other Costs #FLM: dm_fee.other_costs';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_PARAGRAPH_51_AKTIEBOG" IS '¿51/Aktiebog #FLM: dm_fee.paragraph_51_aktiebog';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_PERFORMANCE_FEE" IS 'Performance Fee #FLM: dm_fee.performance_fee';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_PERFORMANCE_FEE_TEXT" IS 'Performance Fee (Desc.) #FLM: dm_fee.performance_fee_text';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_RED_BROKERAGE" IS 'Redemption Brokerage #FLM: dm_fee.red_brokerage';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_RED_FOREIGN_COST" IS 'Redemption Foreign Cost #FLM: dm_fee.red_foreign_cost';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_RED_MARKETING_FEE" IS 'Redemption Marketing Fee #FLM: dm_fee.red_marketing_fee';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_RED_ROUNDING_FACTOR" IS 'Redemption Rounding Factor #FLM: dm_fee.red_rounding_factor';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_RED_SPREAD_CURRENCY" IS 'Redemption Spread Currency #FLM: dm_fee.red_spread_currency';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_RED_SPREAD_RATE" IS 'Redemption Spread Rate #FLM: dm_fee.red_spread_rate';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_RED_TAXES" IS 'Redemption Taxes #FLM: dm_fee.red_taxes';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_RED_TRADE_COST" IS 'Redemption Trade Cost #FLM: dm_fee.red_trade_cost';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_RED_TRADE_COST_ROUNDED" IS 'Redemption Trade Cost (Rounded) #FLM: dm_fee.red_trade_cost_rounded';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_SALES_SUPPORT_FEE" IS 'Sales Support Fee #FLM: dm_fee.sales_support_fee';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_SUB_BROKERAGE" IS 'Subscription Brokerage #FLM: dm_fee.sub_brokerage';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_SUB_FOREIGN_COST" IS 'Subscription Foreign Cost #FLM: dm_fee.sub_foreign_cost';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_SUB_MARKETING_FEE" IS 'Subscription Marketing Fee #FLM: dm_fee.sub_marketing_fee';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_SUB_SPREAD_CURRENCY" IS 'Subscription Spread Currency #FLM: dm_fee.sub_spread_currency';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_SUB_SPREAD_RATE" IS 'Subscription Spread Rate #FLM: dm_fee.sub_spread_rate';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_SUB_TAXES" IS 'Subscription Taxes #FLM: dm_fee.sub_taxes';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_SUB_TRADE_COST" IS 'Subscription Trade Cost #FLM: dm_fee.sub_trade_cost';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_SUB_TRADE_COST_ROUNDED" IS 'Subscription Trade Cost (Rounded) #FLM: dm_fee.sub_trade_cost_rounded';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_TAX_DABONNEMENT" IS 'Tax d''Abonnement #FLM: dm_fee.tax_dabonnement';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_TEGNINGSPROVISION" IS 'Tegningsprovision #FLM: dm_fee.tegningsprovision';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_TER_ACC" IS 'TER (Accounting) #FLM: dm_fee.ter_acc';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_TER_EST" IS 'TER (Estimates) #FLM: dm_fee.ter_est';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_TER_MAX" IS 'TER (Maximum) #FLM: dm_fee.ter_max';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_INDIRECT_TRADE_COST_EST" IS 'Indirect Trade Cost (Estimates) #FLM: dm_fee.indirect_trade_cost_est';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_ADMINISTRATION_FEE_MAX" IS 'Administration fee (Maximum) #FLM: dm_fee.administration_fee_max';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_DIMC_CONTROL_FEE" IS 'DIMC/ Control fee #FLM: dm_fee.dimc_control_fee';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_RED_FEE_AGREED" IS 'Agreed Redemption fee #FLM: dm_fee.red_fee_agreed';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."FEE_SUB_FEE_AGREED" IS 'Agreed Subscription fee #FLM: dm_fee.sub_fee_agreed';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."INV_CLASSIFICATION" IS 'KIID Classification/CI Indicator #FLM: dm_investment.classification';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."INV_COMPOSITE_DATE" IS 'Composite Date #FLM: dm_investment.composite_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."INV_COMPOSITE_NAME" IS 'Composite Name #FLM: dm_investment.composite_name';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."INV_COMPOSITE_SHORT_NAME" IS 'Composite Short Name #FLM: dm_investment.composite_short_name';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."INV_FX_HEDGE" IS 'FX Hedge #FLM: dm_investment.fx_hedge';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."INV_FX_RESPONSIBLE" IS 'FX Responsible #FLM: dm_investment.fx_responsible';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."INV_FX_SPOT" IS 'FX Spot #FLM: dm_investment.fx_spot';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."INV_NEED_ORDER_APPROVAL" IS 'Need Order Approval #FLM: dm_investment.need_order_approval';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."INV_PCT_OF_TNA" IS '% FX Hedge of TNA #FLM: dm_investment.pct_of_tna';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_BOARD_DECISION_DATE" IS 'Board Decision Date #FLM: dm_legal.board_decision_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_CERTIFICATE_CURRENCY" IS 'Certificate Currency #FLM: dm_legal.certificate_currency';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_DISTRIBUTION_COUNTRY" IS 'Distribution Country #FLM: dm_legal.distribution_country';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_EXCHANGE_START_DATE" IS 'Exchange Start Date #FLM: dm_legal.exchange_start_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_FORMATION_EXPENSE" IS 'Formation Expenses #FLM: dm_legal.formation_expense';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_FSA_REGISTRATION_DATE" IS 'FSA Registration Date #FLM: dm_legal.fsa_registration_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_FT_NO" IS 'Sub-fund FSA National ID #FLM: dm_legal.ft_no';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_FULL_LEGAL_NAME" IS 'Full Legal Name #FLM: dm_legal.full_legal_name';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_GIIN" IS 'GIIN #FLM: dm_legal.giin';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_INITIAL_PRICE" IS 'Initial Price #FLM: dm_legal.initial_price';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_ISIN" IS 'ISIN #FLM: dm_legal.isin';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_LAUNCH_DATE" IS 'Launch Date #FLM: dm_legal.launch_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_LEI_CODE" IS 'LEI Code #FLM: dm_legal.lei_code';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_MARKETING_NAME" IS 'Marketing Name (Prisstiller) #FLM: dm_legal.marketing_name';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_MARKETING_NAME_WEB" IS 'Marketing Name (Web) #FLM: dm_legal.marketing_name_web';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_NAME" IS 'Name #FLM: dm_legal.name';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_NOMINAL_PER_CERTIFICATE" IS 'Nominal per Certificate #FLM: dm_legal.nominal_per_certificate';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_OFFERING_END_DATE" IS 'Offering End Date #FLM: dm_legal.offering_end_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_OFFERING_START_DATE" IS 'Offering Start Date #FLM: dm_legal.offering_start_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_ORG_NO" IS 'Sub-fund Organization No #FLM: dm_legal.org_no';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_PRICING_METHOD" IS 'Pricing Method #FLM: dm_legal.pricing_method';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_PSEUDO_SHORT_NAME" IS 'Pseudo Short Name #FLM: dm_legal.pseudo_short_name';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_REGISTER_IN_VP" IS 'Depository Registration #FLM: dm_legal.register_in_vp';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_REPORTING_FT_NO" IS 'Reporting FSA ID #FLM: dm_legal.reporting_ft_no';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_SECURITY_ID" IS 'Security ID #FLM: dm_legal.security_id';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_SUBFUND_LEGAL_STATUS" IS 'Sub-fund Legal Status #FLM: dm_legal.subfund_legal_status';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_SUBFUND_LEGAL_TYPE" IS 'Sub-fund Legal Type #FLM: dm_legal.subfund_legal_type';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_TYPE_OF_CLASS" IS 'Type of Class #FLM: dm_legal.type_of_class';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_VALOREN" IS 'Valoren #FLM: dm_legal.valoren';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_WKN" IS 'WKN #FLM: dm_legal.wkn';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_ASSEMBLY_DATE" IS 'Assembly Date #FLM: dm_merger.assembly_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_BOARD_DECISION_DATE" IS 'Board Decision Date #FLM: dm_merger.board_decision_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_CONTINUED" IS 'Continued #FLM: dm_merger.continued';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_DESCRIPTION" IS 'Description #FLM: dm_merger.description';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_DISCONTINUED" IS 'Discontinued #FLM: dm_merger.discontinued';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_EXCHANGE_RATIO" IS 'Exchange Ratio #FLM: dm_merger.exchange_ratio';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_EXTRAORD_ASSEMBLY_DATE" IS 'Extraord. Assembly Date #FLM: dm_merger.extraord_assembly_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_FSA_APPROVAL_DATE" IS 'FSA Approval Date #FLM: dm_merger.fsa_approval_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_LAST_ACCOUNT_YEAR_END" IS 'Last Account Year End #FLM: dm_merger.last_account_year_end';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_LAST_ACCOUNT_YEAR_START" IS 'Last Account Year Start #FLM: dm_merger.last_account_year_start';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_LAST_OFF_NAV_DATE" IS 'Last Official NAV Date #FLM: dm_merger.last_off_nav_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_LAST_OFF_TRADE_DATE" IS 'Last Official Trade Date #FLM: dm_merger.last_off_trade_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_NAV_ON_CONTINUED" IS 'NAV on Continued #FLM: dm_merger.nav_on_continued';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_NAV_ON_DISCONTINUED" IS 'NAV on Discontinued #FLM: dm_merger.nav_on_discontinued';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_PERFORM_VP_DATE" IS 'Perform VP Date #FLM: dm_merger.perform_vp_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_PROCESS_DESCRIPTION_DATE" IS 'Process Description Date #FLM: dm_merger.process_description_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_TAX_FREE" IS 'Tax Free #FLM: dm_merger.tax_free';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_TAX_IMPLEMENT_DATE" IS 'Tax Implement Date #FLM: dm_merger.tax_implement_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_SECURITY_ID_CONTINUED" IS 'Security ID Continued #FLM: dm_merger.security_id_continued';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."MER_SECURITY_ID_DISCONTINUED" IS 'Security ID Discontinued #FLM: dm_merger.security_id_discontinued';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_CLOSE_OPEN_ENDED" IS 'Close/Open Ended #FLM: dm_structure.close_open_ended';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_FUND_KEY" IS 'Fund Short Name #FLM: dm_structure.fund_key';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_INCOME_DISTRIBUTION" IS 'Income Distribution #FLM: dm_structure.income_distribution';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_INVISION_CODE" IS 'Invision Code #FLM: dm_structure.invision_code';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_MIN_INI_INV_AMT" IS 'Minimum Initial Investment (Amount) #FLM: dm_structure.min_ini_inv_amt';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_MIN_INI_INV_UNIT" IS 'Minimum Initial Investment (Unit) #FLM: dm_structure.min_ini_inv_unit';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_MODEL_PORTFOLIO" IS 'SCD Model Portfolio #FLM: dm_structure.model_portfolio';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_SHORT_NAME" IS 'Short Name #FLM: dm_structure.short_name';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_SUBFUND_STRUCTURE" IS 'Sub-fund Structure #FLM: dm_structure.subfund_structure';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_SUBFUND_STRUCTURE_TYPE" IS 'Sub-fund Structure Type #FLM: dm_structure.subfund_structure_type';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_DM_SUBFUND_TYPE_ID" IS 'Sub-fund Type #FLM: dm_structure.dm_subfund_type_id';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_INTERIM_INCOME_DIST" IS 'Interim income distribution #FLM: dm_structure.interim_income_dist';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_SUBFUND_STATUS_DORMANT" IS 'Sub-fund Status Dormant #FLM: dm_structure.subfund_status_dormant';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_DORMANT_START_DATE" IS 'Dormant Start Date #FLM: dm_structure.dormant_start_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_DORMANT_END_DATE" IS 'Dormant End Date #FLM: dm_structure.dormant_end_date';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_ACTIVE_INACTIVE" IS 'Active/Inactive #FLM: dm_structure.active_inactive';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_SOCIAL_HOUSING" IS 'Almennyttige Boligselskaber #FLM: dm_tax.social_housing';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_SHARE_PRICE_19MAY1993" IS 'Børskurs 19. maj 1993 #FLM: dm_tax.share_price_19may1993';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_EU_SAVINGS_DIRECTIVE" IS 'EU Savings Directive #FLM: dm_tax.eu_savings_directive';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_FINI_NUMBER" IS 'FINI Number #FLM: dm_tax.fini_number';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_FUND_AND_SCHOLARSHIP" IS 'Fonde og Legater #FLM: dm_tax.fund_and_scholarship';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_PRIVATE_FREE_SAVING" IS 'Fri Opsparing (Privat) #FLM: dm_tax.private_free_saving';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_FREE_SAVING" IS 'Fri Opsparing (v¿i¿ring beskattes som kapitalindkomst) #FLM: dm_tax.free_saving';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_MUNICIPALITY" IS 'Kommuner #FLM: dm_tax.municipality';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_SHARE_PRICE_19MAY1993_COR" IS 'Korrigeret Børskurs 19. maj 1993 #FLM: dm_tax.share_price_19may1993_cor';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_ONLY_FLEX_FREE" IS 'Kun Flexinvest #FLM: dm_tax.only_flex_free';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_NTN_NUMBER" IS 'NTN Number #FLM: dm_tax.ntn_number';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_PENSION_SAVING" IS 'Pensionsopsparing #FLM: dm_tax.pension_saving';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_REG_AUSTRAIN_TAX" IS 'Registered Austrain Tax #FLM: dm_tax.reg_austrain_tax';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_REG_GERMAN_TAX" IS 'Registered German Tax #FLM: dm_tax.reg_german_tax';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_COMPANIES" IS 'Selskaber #FLM: dm_tax.companies';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."TAX_COMPANY_TAXATION" IS 'Virksomhedsskatteordning #FLM: dm_tax.company_taxation';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."INV_FX_SPOT_VIA_CLS" IS 'FX spot settled via CLS #FLM: dm_investment.fx_spot_via_cls';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."INV_FX_FWD_VIA_CLS" IS 'FX forward settled via CLS #FLM: dm_investment.fx_fwd_via_cls';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_RESERVED_PM_AGREEMENTS" IS 'Reserved for PM agreements #FLM: dm_legal.reserved_pm_agreements';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_NOTICE_PERIOD" IS 'Notice period (days) #FLM: dm_legal.notice_period';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_LOCK_UP_PERIOD" IS '"Lock-up" period (days) #FLM: dm_legal.lock_up_period';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_SPECIAL_TREATMENT" IS 'Special arrangements and preferential treatment #FLM: dm_legal.special_treatment';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_INVESTOR_GRP1" IS 'Investor Group1 #FLM: dm_legal.investor_grp1';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_INVESTOR_GRP1_PCT" IS 'Breakdown by Investor Group1  (%) #FLM: dm_legal.investor_grp1_pct';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_INVESTOR_GRP2" IS 'Investor Group2 #FLM: dm_legal.investor_grp2';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_INVESTOR_GRP2_PCT" IS 'Breakdown by Investor Group2  (%) #FLM: dm_legal.investor_grp2_pct';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_INVESTOR_GRP3" IS 'Investor Group3 #FLM: dm_legal.investor_grp3';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_INVESTOR_GRP3_PCT" IS 'Breakdown by Investor Group3  (%) #FLM: dm_legal.investor_grp3_pct';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_INVESTOR_GRP4" IS 'Investor Group4 #FLM: dm_legal.investor_grp4';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_INVESTOR_GRP4_PCT" IS 'Breakdown by Investor Group4  (%) #FLM: dm_legal.investor_grp4_pct';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_INVESTOR_GRP5" IS 'Investor Group5 #FLM: dm_legal.investor_grp5';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."LEG_INVESTOR_GRP5_PCT" IS 'Breakdown by Investor Group5  (%) #FLM: dm_legal.investor_grp5_pct';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_MOTIVE_CLASS" IS 'Motive for class #FLM: dm_structure.motive_class';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_OPEN_ACCESS" IS 'Open access #FLM: dm_structure.open_access';
   COMMENT ON COLUMN "D_CERTIFICATE_VER"."STR_ADVISORY_SERVICES_INCL" IS 'Advisory services included #FLM: dm_structure.advisory_services_incl';


  GRANT SELECT ON "D_CERTIFICATE_VER" TO "DWH_DM_READ";
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "APP_GRIP_READ";
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "APP_EOY" WITH GRANT OPTION;
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "APP_EOY" WITH GRANT OPTION;
  GRANT MERGE VIEW ON "D_CERTIFICATE_VER" TO "APP_DR";
  GRANT FLASHBACK ON "D_CERTIFICATE_VER" TO "APP_DR";
  GRANT DEBUG ON "D_CERTIFICATE_VER" TO "APP_DR";
  GRANT QUERY REWRITE ON "D_CERTIFICATE_VER" TO "APP_DR";
  GRANT ON COMMIT REFRESH ON "D_CERTIFICATE_VER" TO "APP_DR";
  GRANT READ ON "D_CERTIFICATE_VER" TO "APP_DR";
  GRANT REFERENCES ON "D_CERTIFICATE_VER" TO "APP_DR";
  GRANT UPDATE ON "D_CERTIFICATE_VER" TO "APP_DR";
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "APP_DR";
  GRANT INSERT ON "D_CERTIFICATE_VER" TO "APP_DR";
  GRANT DELETE ON "D_CERTIFICATE_VER" TO "APP_DR";
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "ODI_CONNECT";
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "APP_EOY" WITH GRANT OPTION;
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "INT_DCLINK" WITH GRANT OPTION;
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "DWH_SYSTEM" WITH GRANT OPTION;
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "DWH_OBI_READ";
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "DWH_DM_STG" WITH GRANT OPTION;
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "APP_WMO";
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "APP_MISC";
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "APP_GRIP_READ" WITH GRANT OPTION;
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "APP_GRIP" WITH GRANT OPTION;
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "APP_FLM" WITH GRANT OPTION;
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "APP_CR" WITH GRANT OPTION;
  GRANT SELECT ON "D_CERTIFICATE_VER" TO "APP_AUTHORITY";
