
  CREATE OR REPLACE EDITIONABLE VIEW dwh_dm."D_TRANSACTION_STATUS_V" ("D_TRANSACTION_STATUS_ID", "TRANSACTION_STATUS_SK", "TRANSACTION_STATUS_CODE", "TRANSACTION_STATUS_NAME", "DWH_CREATED_DATE", "DWH_CREATED_BY", "DWH_CHANGED_DATE", "DWH_CHANGED_BY") AS select transactionstatus.d_transaction_status_id,
       transactionstatus.transaction_status_sk,
       transactionstatus.transaction_status_code,
       transactionstatus.transaction_status_name,
       transactionstatus.dwh_created_date,
       transactionstatus.dwh_created_by,
       transactionstatus.dwh_changed_date,
       transactionstatus.dwh_changed_by
from d_transaction_status transactionstatus
where 1=1;

   COMMENT ON COLUMN "D_TRANSACTION_STATUS_V"."D_TRANSACTION_STATUS_ID" IS 'Primary key on the table D_TRANSACTION_STATUS (sequence generated surogate key)';
   COMMENT ON COLUMN "D_TRANSACTION_STATUS_V"."DWH_CREATED_DATE" IS 'Trigger generated creation date';
   COMMENT ON COLUMN "D_TRANSACTION_STATUS_V"."DWH_CHANGED_DATE" IS 'Trigger generated changed date';


  GRANT SELECT ON "D_TRANSACTION_STATUS_V" TO "DWH_DM_READ";
  GRANT SELECT ON "D_TRANSACTION_STATUS_V" TO "APP_EOY" WITH GRANT OPTION;
  GRANT MERGE VIEW ON "D_TRANSACTION_STATUS_V" TO "APP_DR";
  GRANT FLASHBACK ON "D_TRANSACTION_STATUS_V" TO "APP_DR";
  GRANT DEBUG ON "D_TRANSACTION_STATUS_V" TO "APP_DR";
  GRANT QUERY REWRITE ON "D_TRANSACTION_STATUS_V" TO "APP_DR";
  GRANT ON COMMIT REFRESH ON "D_TRANSACTION_STATUS_V" TO "APP_DR";
  GRANT READ ON "D_TRANSACTION_STATUS_V" TO "APP_DR";
  GRANT REFERENCES ON "D_TRANSACTION_STATUS_V" TO "APP_DR";
  GRANT UPDATE ON "D_TRANSACTION_STATUS_V" TO "APP_DR";
  GRANT SELECT ON "D_TRANSACTION_STATUS_V" TO "APP_DR";
  GRANT INSERT ON "D_TRANSACTION_STATUS_V" TO "APP_DR";
  GRANT DELETE ON "D_TRANSACTION_STATUS_V" TO "APP_DR";
  GRANT SELECT ON "D_TRANSACTION_STATUS_V" TO "ODI_CONNECT";
  GRANT SELECT ON "D_TRANSACTION_STATUS_V" TO "APP_EOY" WITH GRANT OPTION;
  GRANT SELECT ON "D_TRANSACTION_STATUS_V" TO "QUOV";
  GRANT SELECT ON "D_TRANSACTION_STATUS_V" TO "INT_REPORTING";
  GRANT SELECT ON "D_TRANSACTION_STATUS_V" TO "APP_DIMA" WITH GRANT OPTION;
  GRANT SELECT ON "D_TRANSACTION_STATUS_V" TO "APP_SAS";
  GRANT SELECT ON "D_TRANSACTION_STATUS_V" TO "APP_AUTHORITY" WITH GRANT OPTION;
  GRANT SELECT ON "D_TRANSACTION_STATUS_V" TO "APP_GRIP" WITH GRANT OPTION;
  GRANT SELECT ON "D_TRANSACTION_STATUS_V" TO "APP_CR" WITH GRANT OPTION;
