
  CREATE OR REPLACE EDITIONABLE VIEW app_grip_read."V_MODELPORTFOLIOS" ("MO_MPIK", "MO_SOURCE", "MO_MP", "MO_MPNAME", "MO_MPFC6IK", "MO_MPFC6", "MO_MPFC6NAME", "MO_DELIVERY_TIME") AS select "MO_MPIK","MO_SOURCE","MO_MP","MO_MPNAME","MO_MPFC6IK","MO_MPFC6","MO_MPFC6NAME","MO_DELIVERY_TIME" from APP_GRIP.grip_scd_t_model_portfolios;


  GRANT SELECT ON "V_MODELPORTFOLIOS" TO "D022717";
  GRANT SELECT ON "V_MODELPORTFOLIOS" TO "APP_GRIP_READONLY";
  GRANT SELECT ON "V_MODELPORTFOLIOS" TO "D020738";
